### ISSUE TITLE
Failing to actually install

### ISSUE THREAD

**Issue by akerl** [halyard/puppet-asdf#1]
For some reason, the installs are returning exit code 0 but failing to actually install:

```
Notice: /Stage[main]/Asdf/Asdf::Version[python]/Exec[/opt/asdf/bin/asdf install python 2.7.13]/returns: executed successfully
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.0]/returns: executed successfully
```

This affects all languages. I suspect some kind of env issue, though it really ought to cause non-zero exit code.

**Comment by akerl** [comment]
```
❯ ls -la /opt/asdf/installs/ruby/2.4.0
total 0
drwxr-xr-x 2 laker staff  68 May  8 06:24 .
drwxr-xr-x 6 laker staff 204 May  8 06:27 ..
```

**Comment by akerl** [comment]
```
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns:                                  Dload  Upload   Total   Spent    Left  Speed
100 13.5M  100 13.5M    0     0   395k      0  0:00:34  0:00:34 --:--:--  385kruby 2.4.1]/returns:
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: Building with options: ERROR: Please install homebrew for OSX --prefix=/opt/asdf/installs/ruby/2.4.1
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: WARNING: you should use --build, --host, --target
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: WARNING: invalid host type: ERROR:
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: WARNING: you should use --build, --host, --target
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: WARNING: you should use --build, --host, --target
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: WARNING: you should use --build, --host, --target
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: WARNING: you should use --build, --host, --target
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: WARNING: you should use --build, --host, --target
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: checking for ruby... /usr/bin/ruby
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: 	from downloader.rb:1:in `require'
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: checking build system type... Invalid configuration `ERROR:': machine `ERROR:' not recognized
Notice: /Stage[main]/Asdf/Asdf::Version[ruby]/Exec[/opt/asdf/bin/asdf install ruby 2.4.1]/returns: configure: error: /bin/sh tool/config.sub ERROR: failed
```
